services:
  service-b:
    build: ./service-b
    ports:
      - "8081:8080"
    environment:
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_RESOURCE_ATTRIBUTES=service.name=service-b
      - OTEL_TRACES_SAMPLER=always_on
    depends_on:
      - otel-collector

  service-a:
    build: ./service-a
    ports:
      - "8080:8080"
    environment:
      - SERVICE_B_URL=http://service-b:8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_RESOURCE_ATTRIBUTES=service.name=service-a
      - OTEL_TRACES_SAMPLER=always_on
    depends_on:
      - service-b
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
